---
abstract: "Toolforge Mix'n'match tool structures."
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Toolforge-MixNMatch-Struct
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Error::Pure: 0
  Exporter: 0
  Readonly: 0
  Toolforge::MixNMatch::Object: 0.02
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/Toolforge-MixNMatch-Struct/issues
  homepage: https://github.com/michal-josef-spacek/Toolforge-MixNMatch-Struct
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Toolforge-MixNMatch-Struct
version: '0.05'
